- name: install and run nginx
  hosts: [web,cart]
  tasks: 
  - name: install pacakages
    ansible.builtin.pacakge:
      name: nginx
      state: present
  - name: run nginx    
    ansible.builtin.service:
      name: nginx
      state: started
  