- name: install and run nginx
  hosts: [web,cart]
  tasks: 
  become : yes
  - name: install package
    ansible.builtin.package:
      name: nginx
      state: present
  - name: run nginx    
    ansible.builtin.service:
      name: nginx
      state: started
  