#playbook is list of play

- name: PLAY 1
  hosts: locahost
  task:
  - name: PLAY 1 AND TASK 1
    ansible.builtin.debug:
        msg: "Hello from Play 1 and Task 1"

- name: PLAY 2
  hosts: localhost
  task:
    -name:  PLAY 2 AND TASK 2"
    ansible.builtin.debug:
        msg: "Hello from Play 2 and Task 2"

