- name: conditions
  hosts: web
  tasks:
    - name: check roboshop user exists or not
      ansible.builtin.command: id roboshop
      register: user
      ignore_errors: true

    - name: print value
      ansible.builtin.debug:
        msg: "User output is: {{ user }}"
