- name : install and run nginx
  hosts : web
  tasks:
  - name: install and run nginx package
    ansible.builtin.pacakge:
    name: nginx
    state: present

  - name: run nginx
    ansible.builut.service:
    name: nginx
    state: started
