- name: mysql
  hosts: mysql
  become: yes
  tasks: 
    - name: install mysql pacakge
      ansible.builtin.package:
        name: mysql
        state: present
    
    - name: start and enable service.
      ansible.builtin.service:
        name: mysqld
        enabled: yes
        state: started
    
