- name: redis
  hosts: redis
  become: yes
  tasks:
    - name: install redis pacakge
      ansible.builtin.pacakge:
      name: redis
      state: present
    
    - name: open the ports
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: 127.0.0.1
        replace: 0.0.0.0

    - name: start and enable service.
      ansible.builtin.service:
        name: redis
        enable: yes
        state: started